route:
  receiver: "slack"

receivers:
  - name: "slack"
    slack_configs:
      - send_resolved: true
        username: ${USER_NAME}
        channel: ${SLACK_CHANNEL}
        api_url: ${SLACK_API_URL}
